---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: (MANIFEST|FILES)\.json$
      - id: trailing-whitespace
        files: \.(js|rb|md|php|sh|txt|yaml|yml)$
      - id: check-json
        files: \.(json|template)$
      - id: check-yaml
        files: \.(yml|yaml)$
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.7.3'
    hooks:
    -   id: editorconfig-checker
        alias: ec
